
# Runs tests and verifies that the package can be built.
name: debian package publish

# Controls when the action will run.
on:
  workflow_call:
    inputs:
      branch:
        description: 'Target branch'
        default: ${{ github.event.release.target_commitish }}
        type: string
      version:
        description: 'Released version'
        default: ${{ github.event.release.tag_name }}
        type: string
      notes:
        description: 'Release notes'
        default: ${{ github.event.release.body }}
        type: string
      message:
        description: 'Commit message'
        default: ${{ github.event.head_commit.message }}
        type: string
    secrets:
      GPG_KEY:
        required: true
      GPG_KEY_ID:
        required: true
      GIT_COMMITTER_EMAIL:
        required: true
      SSH_ID_RSA:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ${{matrix.operating-system}}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        # operating-system: [ubuntu-22.04, ubuntu-20.04]
        # php-versions: ['5.3', '5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.3']
        # php-versions: ['8.1', '8.2', '8.3']
    name: Build and push package with ${{ matrix.operating-system }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GPG
        uses: diepxuan/.github/.github/actions/gpg-setup@main
        with:
          gpg_key: ${{ secrets.GPG_KEY }}
          gpg_key_id: ${{ secrets.GPG_KEY_ID }}
          committer_email: ${{ secrets.GIT_COMMITTER_EMAIL }}
          committer_name: ${{ github.repository_owner }}

      - name: SSH configuration
        uses: diepxuan/.github/.github/actions/gpg-setup@main
        with:
          ssh_key_id: ${{ secrets.SSH_ID_RSA }}