name: Magento Module update
on:
  workflow_call:
    inputs:
      branch:
        description: 'Target branch'
        default: ${{ github.event.release.target_commitish }}
        type: string
      version:
        description: 'Released version'
        default: ${{ github.event.release.tag_name }}
        type: string
      notes:
        description: 'Release notes'
        default: ${{ github.event.release.body }}
        type: string
jobs:
  magento-module-load:
    runs-on: ubuntu-latest
    outputs:
      m2module: ${{ steps.m2module.outputs.m2module }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate matrix data
        id: m2module
        shell: bash
        run: |
          pkgs=$(ls -l app/code/Diepxuan | grep '^d' | awk '{print $NF}' | while read dir; do echo $dir; done)
          # pkgs=$(ls -l app/code/Diepxuan | grep '^d' | awk '{print $NF}' | while read dir; do cat app/code/Diepxuan/$dir/composer.json | jq -r '.name'; done)
          json=$(printf '%s\n' "${pkgs}" | jq -R . | jq -s -c .)
          # echo "::set-output name=m2module::$pkgs"
          echo "m2module=$json"
          echo "m2module=$(jq -r -c . <<< $json)"
          echo "m2module=$json" >> "$GITHUB_OUTPUT"
      - name: Check
        if: false
        run: jq . <<< '${{ steps.m2module.outputs.m2module }}'
  magento-module-build:
    runs-on: ubuntu-latest
    needs: magento-module-load
    strategy:
      matrix:
        m2module: ${{ fromJSON(needs.magento-module-load.outputs.m2module) }}
    name: Test and Build ${{ matrix.m2module }} module
    steps:
      - name: Check
        if: false
        run: echo ${{ matrix.m2module }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: |
          mkdir -p ~/.ssh
          echo "$SSH_ID_RSA" ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
        env:
          SSH_ID_RSA: ${{ secrets.SSH_ID_RSA }}

      - name: Git configuration
        run: |
          # echo "$GPG_KEY====" | tr -d '\n' | fold -w 4 | sed '$ d' | tr -d '\n' | fold -w 76 | base64 -di | gpg --batch --import
          # echo "$GPG_KEY====" | tr -d '\n' | fold -w 4 | sed '$ d' | tr -d '\n' | fold -w 76 | base64 -di | gpg --batch --import || true
          # echo "$GPG_KEY" | base64 --decode | gpg --batch --passphrase-fd 0 --import -
          # gpg --list-secret-keys --keyid-format=long
          git config global user.email "$GIT_COMMITTER_EMAIL"
          git config global user.name "$GIT_COMMITTER_NAME"
          # git config global commit.gpgsign true
          # git config global user.signingkey $GPG_KEY_ID
        env:
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: ${{ github.repository_owner }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

      - name: Log
        shell: bash
        working-directory: app/code/Diepxuan/${{ matrix.m2module }}
        run: |
          pkgName=$(cat composer.json | jq -r '.name')
          git init
          git remote add origin git@github.com:$pkgName.git
          git fetch -ap
          git checkout main
          git add .
          git status

      - name: Push to repository
        if: false
        run: |
          if [ "$(git status --porcelain=v1 2>/dev/null | wc -l)" != "0" ]; then
            # git add src/debian/control
            git commit -m "Update packages from ${{ matrix.operating-system }} at $(date +'%d-%m-%y')" &&
              # git push https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main ||
              git push ||
              git stash &&
              git pull --rebase &&
              git stash apply &&
              # git push https://${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main || true
              git push || true
          fi
